server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: customer
          uri: http://localhost:8081
          predicates:
            - Path=/customers/** 
        - id: Pay
          uri: http://localhost:8082
          predicates:
            - Path=/pays/** 
        - id: 도서관리
          uri: http://localhost:8083
          predicates:
            - Path=/invetoryManagements/** /dashboards/**
        - id: RENTAL
          uri: http://localhost:8084
          predicates:
            - Path=/rents/** /searchBooks/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path=/customers/** 
        - id: Pay
          uri: http://Pay:8080
          predicates:
            - Path=/pays/** 
        - id: 도서관리
          uri: http://도서관리:8080
          predicates:
            - Path=/invetoryManagements/** /dashboards/**
        - id: RENTAL
          uri: http://RENTAL:8080
          predicates:
            - Path=/rents/** /searchBooks/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080